### ISSUE TITLE
/help command needs to be visible under every app setup instructions menu

### ISSUE THREAD

**Issue by IvanTotti** [fredo-ai/Fredo-Public#125]
Under 1-Email,4-Workflowy and 5-Other main option menu the **/help command is nicely explained : Note: if you feel stuck or want to explore more, try the "/help" command**. But **when you choose option 2- Trello or option 3 - monday the /help command is not written or explained under the setup instructions menu**. I would also add the /help command explanation under all app options menu instructions
![help](https://user-images.githubusercontent.com/105730382/169259896-e602a1b4-7cf6-459b-a9a6-9f1dda9a3bb0.JPG)
**.

**Comment by assafza** [comment]
@IvanTotti  we type the /help command message in later stage after the user is progressing with the onboarding.
