### ISSUE TITLE
Information about max. allowed characters for Fredo - email functionality 

### ISSUE THREAD

**Issue by IvanTotti** [fredo-ai/Fredo-Public#128]
The **user should be informed under option number 1. Email - That fredo supports  email notes with max. number of characters ( for example 1000)**.  

**Also Fredo should react somehow if note with more than max allowed characters is sent**.  
When the user tries to send a longer note to his email right now there is no action from Fredo  = email is not sent and there is also no error message showing.  

**Example of possible Fredo reaction when user tries to send longer than allowed note  -  **The number of allowed characters was exceeded - Email was not sent .****

**Comment by assafza** [comment]
@JerryVDP few questions:
1. what is the max allowed chars we can send? 
2. is it a whatsapp limitation?
3. if so we should apply it to all platforms although only email is the relevant platform with this issue given the nature of emails being longer than just a task management platform.
