### ISSUE TITLE
Convert voice to text

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#134]
@JerryVDP UPDATED TASK SPECIFICATION ON SPEECH TO TEXT.

Google cloud account:
https://cloud.google.com/
email: rgr.projects1@gmail.com
p/w: ask Assaf/Liat

Google API: https://speech.googleapis.com/v1p1beta1/speech:recognize?key={{YOUR API KEY}}
Please see the Postman workspace with a successful request: https://lively-station-25649.postman.co/workspace/4f8cb1e9-3cd3-4ea1-83ac-906cd70c9cd0/request/21719145-4ad41576-cf9e-4fc0-87e1-8b44568e1f53

LOOKSLIKE WE WILL NEED TO CONVERT THE VOICE INTO A URI BEFORE PASSING IT TO API.

Miro Flow:
- https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764529559472302&cot=14

Mixpanel: 
- Add a new event when user start it: TRANSCRIBE START
- Add event when user complete it: TRANSCRIBE SUCCESS
- https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0

Specifications:
- Should exist in all help menus for all platforms (🎙 **/transcribe** converts audio into text) https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764529561405600&cot=14

**Comment by JerryVDP** [comment]
If it's available in Twilio then ~ 4 hours

**Comment by assafza** [comment]
Adding here the API doc related to recording transcribed:
https://www.twilio.com/docs/voice/api/recording-transcription

**Comment by JerryVDP** [comment]
@assafza 
I think we can go ahead and signup to Google.

**Comment by assafza** [comment]
@liatzionimorad after you sign up for Google cloud we will need the access to get the right tokens and all that to create the PAI.

@JerryVDP I will prepare tomorrow the flow for this. in the mean time establish some new command that can accept the audio file and output the transcription.
