### ISSUE TITLE
Different welcome messages based on first message text

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#136]
Consider a way to show different onboarding to users based on the first message text.
(e.g. “hi” will be replied with “xxx” welcome message, “Hello” will be replied with “yyy” welcome message)

**Comment by assafza** [comment]
@JerryVDP can you estimate the complexity of this feature?

**Comment by JerryVDP** [comment]
@assafza Easy Peasy.
Whenever you choose to proceed with this idea, please prepare a Google Sheet with the following columns:
1. Initial trigger word (e.g. "Hi", case insensitive).
2. Proper response for that trigger

And I'm gonna need a default fallback response for other undefined triggers.

**Comment by assafza** [comment]
AMazing thanks @JerryVDP
