### ISSUE TITLE
Option to automatically have different flows based on a word input

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#147]
As an admin I would want the ability to be able to create different welcome message through Json file.

Example of a json file:
{
     user_message: "hello",
     welcome_message: "xxxxxxxxx"
},
{
     user_message: "hi",
     welcome_message: "yyyyyyyyy"
},
{
     user_message: "howdy",
     welcome_message: "zzzzzzzzzz"
},

In the long run we wish to have the ability to have different onboarding flows based on keyword. @JerryVDP can you think of a technical way to implement something to support this need?

**Comment by JerryVDP** [comment]
@assafza 
Could you please create a simple Google Sheet file and send it to me?
The sheet should be publicly accessible via sharable URL

**Comment by assafza** [comment]
@JerryVDP here is go: 
https://docs.google.com/spreadsheets/d/1P8YJt3U6PCiFRVXTbvZgZaqeh-rP_aaS6OVUzCQiu7E/edit?usp=sharing
