### ISSUE TITLE
MixPanel: Add "tasks per backend" pie chart

### ISSUE THREAD

**Issue by ripper234** [fredo-ai/Fredo-Public#149]
As an admin, I'd like to see statistics how how many tasks were added using each backend (WF/Trello/Email/Monday/...) in the last X days (X = 7? 30?).

I think a good way to show this is via a pie chart in our MixPanel, with both absolute numbers & percentages.

**Comment by assafza** [comment]
@ripper234 @liatzionimorad 
I have added this to the main dashboard. now you can see in a pie chart: MAU per platform, Items per platform.
https://mixpanel.com/project/2661337/view/3198761/app/dashboards#id=3179943
