### ISSUE TITLE
Mixpanel events for other command list flows

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#155]
Add new events based on mixpanel doc: 
https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0

**Comment by assafza** [comment]
@JerryVDP  The following event is yet to be created : "NEW HASHTAG MAP CREATED"

**Comment by JerryVDP** [comment]
It's already implemented under the original name `NEW_LIST_MAP_HASHTAG_CREATE`.

**Comment by assafza** [comment]
@JerryVDP oh ok so I guess its not working? I haven’t seen this event.
