### ISSUE TITLE
Updating users what has changed since they logged in

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#160]
update message on new version is currently being sent the moment we release the release notes from GitHub.
it is sent ONLY to users who have chatted with Fredo in the last 24 hours as to Whatsapp guidelines.

We want to make sure ALL users get this message.
In order to do so, lets mark users that did not receive the latest update on new version and make sure they get it once they send a new message and connect again.

It should work like this:
- day 0: last message from user
- day 3: release note sent
- day 3: user is not receiving the release note since we are not allowed
- day 5: user sent message to Fredo. after 1 hour user should receive the release note message from Day 3.

**Comment by JerryVDP** [comment]
@assafza 
This will start working only from the next version, because in this version we will only start saving all the relevant information (when the user was last active, the user's current version, the release notes content, etc...)

**Comment by assafza** [comment]
@JerryVDP ok sure make sense - but is there a way to test it?

**Comment by JerryVDP** [comment]
@assafza 
There isn't a way to test it on a Whatsapp bot, I tried the different "blocks" of code on my end and each block worked as expected.
The ultimate end-to-end test would be test it in a real release
