### ISSUE TITLE
Message template for  bug

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#165]
Message (Bug): Please describe what is your issue. (you can use free text, try to elaborate as much as possible)
Message (Error): Ooops....🤒 It's not you, it's us. Seems like we ran into a problem. 
                  Note: in case you feel stuck or want to explore more, try the "/help" command.

Button text: "cancel and go back" 
Action: exit current flow and go back to default.

**Comment by JerryVDP** [comment]
The task is partially done, Didn't do the error one, we should create a global command first (maybe \reset?) and then show it as a button.
Let's close this issue and create a new issue with the global command.
