### ISSUE TITLE
New command /learn

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#182]
will present a link to the Fredo knowledge base: https://bit.ly/3yfBIYS
here is a flow: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764528670249153&cot=14
Help menu: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764519491476452&cot=14

**It should be in every menu in all platforms.**

**Comment by JerryVDP** [comment]
Should this be added only to the help menu of workflowy? or any other responders as well?
@assafza

**Comment by assafza** [comment]
@jerryvdp To all responders for now. later on we might want to show
different link in the response to this command. trello will go to trello
help center, wf to wf help center and so on...

**Comment by assafza** [comment]
@JerryVDP this should also be added to all platforms help menu.
I see on the Email platform its not showing. please make sure its in all platforms:
<img width="719" alt="Screen Shot 2022-07-13 at 20 16 04" src="https://user-images.githubusercontent.com/25544824/178792400-91618c49-f8d1-4e9f-a86f-14b370055f49.png">
