### ISSUE TITLE
Workflowy onboarding glitch for first item

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#193]
First message is not send through
see image:
![Screen Shot 2022-07-05 at 12 41 16](https://user-images.githubusercontent.com/25544824/177299819-272e4b67-feb9-446f-88f9-c30817bd05bc.png)

**Comment by JerryVDP** [comment]
Something was wrong with the shared link. Presumably, the API can't work with nested lists.
@assafza you can close this for now.
