### ISSUE TITLE
Cant send items to Workflowy integration

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#194]

**Comment by JerryVDP** [comment]
Could you provide an explanation and example?
@assafza

**Comment by assafza** [comment]
simply cant send anything @JerryVDP 

![Screen Shot 2022-07-05 at 13 26 27](https://user-images.githubusercontent.com/25544824/177307979-bd7470bf-d6f5-486e-9328-f85ff6743587.png)

**Comment by JerryVDP** [comment]
Something was wrong with the shared link. Presumably, the API can't work with nested lists.
@assafza you can close this for now.
