### ISSUE TITLE
bug report should be sent to connect@fredo.io

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#195]

**Comment by liatzionimorad** [comment]
@assafza  it's connect@fredo.ai

@JerryVDP please change to correct address

**Comment by assafza** [comment]
@JerryVDP cant send bugs
![Screen Shot 2022-07-06 at 8 53 03](https://user-images.githubusercontent.com/25544824/177478664-8064923d-d135-4f92-8c2b-abbece0d01dc.png)
