### ISSUE TITLE
enable sending of images/files to #tagged list in All platforms

### ISSUE THREAD

**Issue by liatzionimorad** [fredo-ai/Fredo-Public#206]
When user upload an image or file with #hashtag it should add it to the mapped list.

@JerryVDP let us know if this is possible with WhatsApp

**Comment by assafza** [comment]
I could not send image to a tagged list. Am I doing something wrong?
@JerryVDP 

<img width="913" alt="Screen Shot 2022-08-18 at 15 31 04" src="https://user-images.githubusercontent.com/25544824/185396859-f623c294-c4f3-46b1-9087-b8acf3455b73.png">
