### ISSUE TITLE
Send whatsapp to non-contact number

### ISSUE THREAD

**Issue by adidacta** [fredo-ai/Fredo-Public#212]
Sending WhatsApp can only be done via contact or a unique link in the format https://wa.me/xxxxxxxx (x=phone number).
Fredo should return such a link for any number sent to it, so a user can click it and send a whatsapp.
Optional: use number in clipboard instead of pasting it in the chat

@assafza, what do you think about this?

**Comment by assafza** [comment]
solved in #237
