### ISSUE TITLE
Successful transcribe should also save the text as a new text item + link to the audio file

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#221]
Link to Miro: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764529560852927&cot=14

@JerryVDP

**Comment by assafza** [comment]
@JerryVDP It did not work for me, sure it was released to testing?

**Comment by JerryVDP** [comment]
@assafza 
It's working for me, could you please provide a full scenario where it doesn't work?
