### ISSUE TITLE
/help menu not working in test version

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#223]
<img width="952" alt="Screen Shot 2022-08-07 at 14 45 14" src="https://user-images.githubusercontent.com/25544824/183288976-65a302a9-6593-4adb-98ab-8711a7a29ac7.png">

**Comment by JerryVDP** [comment]
![image](https://user-images.githubusercontent.com/99589825/183282844-0f037c3e-6e9e-4e0b-a8da-3cab058b33c1.png)
Please provide more information
