### ISSUE TITLE
Show trascribe file URL as "(audio)" hyperlink

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#238]
when there is a new audio item sent to platform replace the audio link with hyperlink audio.
See example how it should look in workflowy:

<img width="315" alt="Screen Shot 2022-08-21 at 7 37 32" src="https://user-images.githubusercontent.com/25544824/185775734-094101a0-5464-4411-87ab-a2a0369d6c19.png">

**Comment by JerryVDP** [comment]
Only Workflowy supports hyperlinks, so I added it only to Workflowy.
