### ISSUE TITLE
validation functionality for reading key:value register of user

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#243]
1. We need to add validation mechanism to make sure we could translate the text in the object.
2. In case we could not do so we should show a generic message for error:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764519386030921&cot=14

**Comment by assafza** [comment]
@JerryVDP How do you suggest we should test this?
I think this is something you should test on your end no?

**Comment by JerryVDP** [comment]
@assafza You can't test it.
I test it on my end (by simulating a situation where the encoding fails) and it worked as expected.
