### ISSUE TITLE
Technical issue: Don't save user's last state if user is already in a helper Responder

### ISSUE THREAD

**Issue by JerryVDP** [fredo-ai/Fredo-Public#252]
We have a few "helper" responders like:
 - Logout
 - Reminder
 - Transcribe
 - Bug

Before the user actually moves to a helper responder, Fredo saves the user's last state (his last responder) to know where to go back to after the user finishes with the helper responder.

This is subject to an issue if the user types "/reminder" and then in the middle of the reminder flow the user types "/reminder" again, it would overwrite the user's last state with "Reminder", so the user can never get back to his original state, and worse than that, if a user types "/help" or "/cancel" then the command is forwarded to the user's last state, which could trigger an infinite recursive call that could lead to a user's data destruction.

**Comment by assafza** [comment]
@JerryVDP very clear and informative thanks
