### ISSUE TITLE
Add non_contact item in help menu + flow

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#255]
📬 11. /non-contact - Send WhatsApp message to numbers without saving them in your contacts

Miro flow:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764532271926412&cot=14

**Comment by JerryVDP** [comment]
@assafza 
This is a new feature.
Do we want to add more features to this sprint (5.2.0)? I think it should be moved to 5.3.0
