### ISSUE TITLE
Bug inside Transcribe as stand alone

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#259]
Looks like I was able to create an infinite loop:
1. selecting the "other" which was probably the transcribe stand alone
<img width="952" alt="Screen Shot 2022-08-31 at 2 03 40" src="https://user-images.githubusercontent.com/25544824/187558511-f8be81dc-cbcc-47f1-ba79-29fa2b896600.png">

2. onboarding with first audio
<img width="935" alt="Screen Shot 2022-08-31 at 2 03 28" src="https://user-images.githubusercontent.com/25544824/187558594-fd3b2c25-e94e-472f-b21e-2c98823aef76.png">

3. Clicked Help and all crashed
<img width="954" alt="Screen Shot 2022-08-31 at 2 03 20" src="https://user-images.githubusercontent.com/25544824/187558644-8565386a-c40b-41bc-a13a-7c83947fde75.png">

4. Mixpanel is showing me few thousands of MESSAGE events sent in this exact moment
<img width="807" alt="Screen Shot 2022-08-31 at 2 06 29" src="https://user-images.githubusercontent.com/25544824/187558783-5ade384b-ac58-4a98-a650-de938283914d.png">

Also, why logout is taking me to trello setup and not the generic welcome message?

**Comment by JerryVDP** [comment]
@assafza 
What help message should Fredo output in this case?

**Comment by assafza** [comment]
I’m not near computer.
On Miro please look at the panel with all the help menus you will see there
the menu for Transcribe.
@jerryVDP

**Comment by assafza** [comment]
@JerryVDP 
1. I am still not able to click on Help Or Learn after feedback
2. /help is not accessible should open menu: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764531298094932&cot=14
3. /logout is taking me to Trello message
