### ISSUE TITLE
Feature adoption flow

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#311]
When user is not using specific feature (we will identify this on Mixpanel) we will send him a message through Make.com (automation).
The message is a template which will trigger 3 optional buttons.

1. Create template for the first message in Twilio
2. Expose new POST API /feature_adoption. this API will generate the template message from point num 1
3. Implement the flow https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764535272571966&cot=14
4. Implement mixpanel events(Implement properties same as we did in "HOW TO flow":
https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0

**Comment by JerryVDP** [comment]
Still not ready, but eventually the endpoint for this will be:
**POST** request to "**/feature-adoption**" with "**phone**" parameter (in the following format: "972XXXXXXXX").

**Comment by assafza** [comment]
@JerryVDP  Something broke after I activated the flow:
1. Connected to Trello
2. Send feature adoption message
3. "Show me" option
4. Send feature adoption message again
5. "Maybe later" selected
6/ "in 1 hour"
7. Send feature adoption message again
8. select "No need"
9. flow is in deadlock
![WhatsApp Image 2022-11-20 at 5 47 40 PM](https://user-images.githubusercontent.com/25544824/202911884-28592ca3-5b50-495b-afc6-8a84b85be68b.jpeg)

![WhatsApp Image 2022-11-20 at 5 45 45 PM](https://user-images.githubusercontent.com/25544824/202911892-a622bb53-5a7a-4c01-9c79-0594456b085a.jpeg)

**Comment by assafza** [comment]
@JerryVDP 
Also, looks like it created a bug in the Mixpanel events - there are thousands of events sent for some reason:
![Screen Shot 2022-11-20 at 17 53 12](https://user-images.githubusercontent.com/25544824/202912014-5aac6b74-3eea-44b2-a0de-854d59775f45.png)

**Comment by assafza** [comment]
@JerryVDP here is the updated message template: 
"There are more features to explore with Fredo. 
Would you like me to show you?"
https://console.twilio.com/us1/develop/sms/senders/whatsapp-templates/HTd857f35b4340da56f7e78be693662f5c?frameUrl=%2Fconsole%2Fsms%2Fwhatsapp%2Ftemplates%2FHTd857f35b4340da56f7e78be693662f5c%3Fx-target-region%3Dus1

**Comment by assafza** [comment]
@JerryVDP 

1. Please break a line
<img width="589" alt="Screen Shot 2022-11-23 at 21 11 45" src="https://user-images.githubusercontent.com/25544824/203628649-887df076-a8cd-456c-aeb8-851cf25fafda.png">
2. Mixpanel events are still being sent in thousands after I sent to myself the feature adoption message:
<img width="493" alt="Screen Shot 2022-11-23 at 21 13 47" src="https://user-images.githubusercontent.com/25544824/203628999-2d92f17a-ec7f-454c-abef-184bf0e7200f.png">
