### ISSUE TITLE
No video after logout

### ISSUE THREAD

**Issue by WeKeren** [fredo-ai/Fredo-Public#316]
logout from the
<img width="556" alt="Screen Shot 2022-10-26 at 9 55 33 AM" src="https://user-images.githubusercontent.com/113281951/197956285-18e9fb36-46eb-4d8e-86b5-357a8cd1eddf.png">

**Comment by assafza** [comment]
@WeKeren there should not be a video after logout. why do you think it should?

**Comment by WeKeren** [comment]
When I logout I see my login options again the "welcome to Fredo" . If not there then where does the video appear?

**Comment by liatzionimorad** [comment]
@assafza  in our view ( Keren's and mine) when I logout i return to the state I was as if I am a new user, since all data related to me is gone...
So if I am a new user I would expect the video.
I think it can be useful if I think I made a mistake and wants to start over.
What ever you decide

**Comment by assafza** [comment]
@liatzionimorad @WeKeren I do not see any video after I logout. can you share more info?
