### ISSUE TITLE
transcribe failed: no replay from fredo no transcription 

### ISSUE THREAD

**Issue by WeKeren** [fredo-ai/Fredo-Public#317]
send voice message no connected to any platform 
<img width="586" alt="Screen Shot 2022-10-26 at 10 02 15 AM" src="https://user-images.githubusercontent.com/113281951/197957787-718f13ac-b245-452f-9491-3306b5aa1f24.png">

**Comment by assafza** [comment]
@WeKeren can you please add the voice message file?

**Comment by JerryVDP** [comment]
@assafza 
_This API method requires billing to be enabled. Please enable billing on project #599165864608 by visiting https://console.developers.google.com/billing/enable?project=599165864608 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry._
