### ISSUE TITLE
wrong response - "no need"

### ISSUE THREAD

**Issue by WeKeren** [fredo-ai/Fredo-Public#318]
in the menu where I chose "no need" or "more please" : 
1 i clicked "more please"- all OK
2 I clicked "no need" - the result did not write anything 

<img width="575" alt="Screen Shot 2022-10-26 at 10 14 31 AM" src="https://user-images.githubusercontent.com/113281951/197959459-04981bd5-4416-4a87-aff2-18d5e4c2c2e7.png">
<img width="587" alt="Screen Shot 2022-10-26 at 10 17 03 AM" src="https://user-images.githubusercontent.com/113281951/197959722-ffa1726f-2456-41bc-ae39-c1778790ad7e.png">

**Comment by JerryVDP** [comment]
@assafza 
Fredo can't handle replies, the no need text was intended to a message that was sent previously and not to the latest message.
What is the desired behavior?

**Comment by assafza** [comment]
Closed and handled in another ticket
