### ISSUE TITLE
Mapping with hashtag not working in all platforms

### ISSUE THREAD

**Issue by WeKeren** [fredo-ai/Fredo-Public#323]
I tried to use # to map a new borad\ link
the action failed - there was no response from Fredo on this action.
Tried it after pressing show more skills:

Other Skills-show more- #shopping your_board_link example- field (nothing happens) in all platform

<img width="584" alt="Screen Shot 2022-10-29 at 9 12 22 PM" src="https://user-images.githubusercontent.com/113281951/198869332-c6baba0b-7611-46f8-b157-593448c0ff7c.png">
<img width="575" alt="Screen Shot 2022-10-29 at 9 13 04 PM" src="https://user-images.githubusercontent.com/113281951/198869355-45e43d8e-1237-4027-8cdd-5d8758c7e610.png">

**Comment by JerryVDP** [comment]
@assafza @liatzionimorad 
There are 2 bugs here:
1. Fredo didn't respond to general queries while in how_to flow.
2. Fredo didn't respond to replies - There's nothing we can do about that, Fredo will always process the user input as an answer to the last message.
