### ISSUE TITLE
Admin should be able to manually text users (e.g. about critical errors)

### ISSUE THREAD

**Issue by ripper234** [fredo-ai/Fredo-Public#34]
As an admin, when a critical error affects at least 20-50% of our users I want to be able to send ALL users of the system a custom text message explaining the situation, ETA to resume working, etc.

1. This could ride on the same mechanism as Version Update messages
2. But I think we might want to make sure this reaches ALL users, even those that haven't sent a message to the bot in the last few days.

**Comment by ripper234** [comment]
I estimate this as a **small** feature.

**Comment by liatzionimorad** [comment]
@sgino209 :  an email may be applied as a fallback in case that texting didn’t end up well (Twilio responded with an error)

**Comment by assafza** [comment]
We have that ability now using the customer.io interface
