### ISSUE TITLE
Reminder text should also capture text is break by lines

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#344]
See example: 
<img width="880" alt="Screen Shot 2022-11-16 at 21 47 13" src="https://user-images.githubusercontent.com/25544824/202279572-0753588c-bf81-4882-ae5c-94cce733456f.png">

**Comment by assafza** [comment]
@JerryVDP 
1. Its not showing the button for snooze. here is a link to the template: https://console.twilio.com/us1/develop/sms/senders/whatsapp-templates/HT6b82d4a2744ba71330bae98d21049714?frameUrl=%2Fconsole%2Fsms%2Fwhatsapp%2Ftemplates%2FHT6b82d4a2744ba71330bae98d21049714%3Fx-target-region%3Dus1
2. the reminder should be in Bold font

**Comment by lotem-vanunu** [comment]
i see when there are some lines the "snooze" button doesn't appear
![WhatsApp Image 2023-01-03 at 11 11 21 AM](https://user-images.githubusercontent.com/98812015/210328557-c5791e84-ef4a-485c-ba5e-e0ab6f42fa7d.jpeg)

do you know why it happens?
