### ISSUE TITLE
/howto Failed on all platforms

### ISSUE THREAD

**Issue by WeKeren** [fredo-ai/Fredo-Public#348]
Transcribe -Failed 
Reminders- Failed 
Other skills- Failed 

<img width="584" alt="Screen Shot 2022-11-16 at 10 10 11 PM" src="https://user-images.githubusercontent.com/113281951/202471616-436099c5-6824-4214-b1db-6ae1a857a1aa.png">
<img width="579" alt="Screen Shot 2022-11-16 at 10 14 51 PM" src="https://user-images.githubusercontent.com/113281951/202471651-d821f8e3-52fc-4e17-a107-33c379df1358.png">
<img width="590" alt="Screen Shot 2022-11-17 at 4 15 03 PM" src="https://user-images.githubusercontent.com/113281951/202471665-4a9ab6ce-5968-4895-9bf6-b9eb1dd90e98.png">

<img width="580" alt="Screen Shot 2022-11-16 at 10 14 18 PM" src="https://user-images.githubusercontent.com/113281951/202471639-bc851f7c-4321-4af8-ba5f-65c08bca6e2c.png">
<img width="586" alt="Screen Shot 2022-11-16 at 10 15 13 PM" src="https://user-images.githubusercontent.com/113281951/202471658-a95b717b-62a4-452a-8163-8c035ca02fb8.png">

<img width="584" alt="Screen Shot 2022-11-16 at 10 13 33 PM" src="https://user-images.githubusercontent.com/113281951/202471628-53b0be3b-578f-4854-b0bf-7393141e0ac9.png">

**Comment by assafza** [comment]
Solved
