### ISSUE TITLE
Workflowy & Monday Failed to send pictures videos emoji + Failed to send contact

### ISSUE THREAD

**Issue by liatzionimorad** [fredo-ai/Fredo-Public#352]
when Connected to  Monday and trello failed to add images and failure in contact sending
![image](https://user-images.githubusercontent.com/79567202/203250814-c32c74c4-4d06-4daa-9a5e-baa59b86db5c.png)

**Comment by JerryVDP** [comment]
@liatzionimorad 

1. The title says "Workflowy & Monday" while the description says "Monday and trello", which is it?
2. You have supplied examples for the media files failures, however no examples were submitted for the contact issue.

**Comment by liatzionimorad** [comment]
@JerryVDP it was Monday and workflowy

about 2 - just test it please

**Comment by liatzionimorad** [comment]
![WhatsApp Image 2022-11-22 at 09 24 46](https://user-images.githubusercontent.com/79567202/203301083-12b9a3bc-aa28-4479-92a4-753d1c3609f0.jpeg)
