### ISSUE TITLE
check support on GPTCHAT

### ISSUE THREAD

**Issue by liatzionimorad** [fredo-ai/Fredo-Public#360]
[10:13, 7.12.2022] רון גרוס: גב, בלי קשר לפקודת tldr, אני אישית (ואולי כל מיני אחרים, זה נושא פופולארי), אשמח לקבל פשוט ממשק general purpose נוח לדבר בו עם ה gptchat.

כלומר פשוט לכתוב

gpt <text>

וזה יעבור ל gptchat.
מחיפוש קצר שעשיתי הדרך היחידה לדבר עם gptchat זה דרך האתר שלהם, זה ממש לא נוח בשוואה לוואטסאפ. אז אשמח למצוא דרך נוחה לדבר עם ה AI.

למעלה שמתי לינק לקוד שלכאורה מחבר אותו לוואטסאפ, אבל הבנתי אם זה deployed כבר איפשהו, או שזה מיועד רק למפתחים בשלב זה.

אם נממש כזה זריז לדעתי אפשר למנף את הבאז שיש כרגע על gptchat ולהשיג משתמשים דרך זה.
[10:25, 7.12.2022] רון גרוס: ואולי גם שה summarize/transcribe ידעו לקבל כקלט הרצאות יוטיוב או קטעים מסאונדקלאוד וכו'.

1. גם אופציה שיתמלל נגיד הרצאה שלמה ביוטיוב.
2. ואחכ גם אופציה שיאמלק לי אותה כבר.
טובhttps://indianexpress.com/article/technology/tech-news-technology/god-in-a-box-ai-chatbot-gpt-3-5-whatsapp-how-to-signup-what-it-does-8308254/

נגיד מישהם משיקים בוט וואסטאפ ייעודי לדיבור עם GPTCHAT, והולכים לגבות 9$ לחודש.

*מה הסיכוי שלנו לשים על זה יותר משאבים, ולתפור כאן פיתרון מהיר ולשחרר תמיכה כלשהי ב-GPTCHAT "כמה שיותר מוקדם" (נגיד בעוד שבוע)?
אני חושב שיש כאן סיכוי ל-first mover advantage - שהשחקנים הראשונים שייכנסו יוכלו לזכות בקלות בהרבה פירסום ומשתמשים.

**Comment by assafza** [comment]
handled in #387
