### ISSUE TITLE
Mixpanel event property "platform" is often contain weird values

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#363]
These are the values I see which are weird:
![WhatsApp Image 2022-12-13 at 8 53 17 AM](https://user-images.githubusercontent.com/25544824/207247392-e631ab21-5fd8-44d7-9ce1-3376b2824457.jpeg)

Attaching here all the events that has those values:
[events-export-2648676-1670914451699.csv](https://github.com/fredo-ai/Fredo-Public/files/10215269/events-export-2648676-1670914451699.csv)

**Comment by JerryVDP** [comment]
Events lists:

- [ ] TRANSCRIBE_FAILED
- [ ] TRANSCRIBE_START
- [ ] MENU_OPENED
- [ ] REMINDER_CREATED
- [ ] HOWTO_START
- [ ] TRANSCRIBE_SUCCESS
- [ ] NON_CONTACT_NUMBER
- [ ] HOWTO_END
- [ ] HOWTO_REMINDER
- [ ] HOWTO_CONTACT
- [ ] HOWTO_COLLECT
- [ ] HOWTO_PLATFORM_CANCEL
- [ ] HOWTO_COLLECT_SELECT_PLATRFORM
- [ ] HOWTO_COLLECT_MORE
- [ ] HOWTO_TRANSCRIBE
- [ ] PMF_SURVEY_COMPLETE
- [ ] HOWTO_MORE
