### ISSUE TITLE
Email verification code improvement

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#366]
1. Add a big button "Verify Email" to the end of the email template
2 Button should link to Whatsapp + append the pre-text with the 4 digit code. that way user can click -> redirected to Fredo bot on whatsapp -> the code already in the text box he just need to send.
See example: https://wa.me/972525277961?text=5555

**Comment by JerryVDP** [comment]
<img width="342" alt="Screenshot 2022-12-18 at 13 16 40" src="https://user-images.githubusercontent.com/99589825/208295331-8e3c7842-33b9-4923-86f3-eaede357d896.png">

**Comment by assafza** [comment]
1. I see the email button looks like hyper link
![Screenshot 2022-12-26 at 14 41 04](https://user-images.githubusercontent.com/25544824/209550226-ab681f74-33a2-4ddd-9334-1d8e0a3f7c69.png)

2. the redirect link takes to the wrong phone number. it should redirect to the live number curerntly for some reason it redirects to my phone number
https://api.whatsapp.com/send/?phone=972507891914&text=7718&type=phone_number&app_absent=0
