### ISSUE TITLE
reminder flow loop

### ISSUE THREAD

**Issue by liatzionimorad** [fredo-ai/Fredo-Public#367]
נבחר אימייל כממשק
בהתאם לבקשה נשלח מייל
משם והלאה הודעות שגיאה של רימיינדר
![image](https://user-images.githubusercontent.com/79567202/207576939-e9d17448-81e9-44ca-8b3d-346bec927946.png)
![image](https://user-images.githubusercontent.com/79567202/207576998-4bd0355f-c5f5-4023-bd14-eaa246304922.png)
![image](https://user-images.githubusercontent.com/79567202/207577070-d9a71a12-8293-4e50-aa85-4c3e32266d42.png)

**Comment by assafza** [comment]
Solved
