### ISSUE TITLE
New onboarding message

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#377]
1. new welcome flow (instead of a single message with all options)
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764518853344962&cot=14

2. Need to add Mixpanel event for the first added message when user select skill:
WELCOME SKILL
Link: https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0

**Comment by lotem-vanunu** [comment]
hi @assafza, did u add the new buttons to Twillo?
which text i need to send  to twillo?

**Comment by assafza** [comment]
@lotem-vanunu 
Yes I added it on twilio.
it worked after I added the custom onboarding message. here: https://docs.google.com/spreadsheets/d/1P8YJt3U6PCiFRVXTbvZgZaqeh-rP_aaS6OVUzCQiu7E/edit#gid=0

@JerryVDP can you explain lotem about this mechanisem of custom onboarding?
Also, how can we test this as fallback message without messing the production version?

**Comment by assafza** [comment]
@lotem-vanunu it does not send the Mixpanel event -  "Need to add Mixpanel event for the first added message when user select skill:
WELCOME SKILL
Link: https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0"
