### ISSUE TITLE
Contact is still printing two time (in Monday & Trello)s

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#390]
![WhatsApp Image 2022-12-29 at 7 33 45 PM](https://user-images.githubusercontent.com/25544824/209990696-00eb0da7-ef12-4f48-9d33-d1b5b0b2450f.jpeg)

**Comment by JerryVDP** [comment]
Improved logs + implemented potential fix.
We'll keep an eye on this
