### ISSUE TITLE
Show privacy policy template logic

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#404]
All users should approve Fredo's privacy policy.

In order to do so, we need to explicitly ask them for their approval.

1. save for every user profile a field called "privacy_approval" it should contain the date of the signing + IP address if possible to get from whatsapp.
privacy_approval : {
   sign_date : {{date and time}},
   IP: {{ip address}},
}
this object should be saved for every user.

2. If user is coming from the website registration -> he already signed the policy. in that case we need a way for the website registration to send user data with an API to identify those users as users who already signed and approved the privacy policy and not show it to them inside the bot. If user exist, just mark the timestamp && Ip for object privacy_approval. if user not exist create new object for the user with the details.
**Need to get an API for posting this data**

3. For every other user attempting to send anything new to fredo we should check if he has a date value in "privacy_approval.sign_date". in case he does not have a value we should present him with this privacy flow first:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764542655636864&cot=14
**In case this is the first message user is sending to fredo ever and there is not a record and also old users that never signed this privacy should now approve it** meaning users will get the privacy policy request after their first item sent successfully. (for that we can save in the DB the date of the first sent item.

@JerryVDP please review and let me know.

**Comment by JerryVDP** [comment]
API Endpoint:
POST: /privacy-policy
Params: phone=[phone number, Example: 97252555555]

**Comment by assafza** [comment]
after the message showed and I approved it -> it did not continue to create the reminder. if its easier you can complete the current operation and then show the privacy policy message. 
<img width="934" alt="Screenshot 2023-01-16 at 9 47 39" src="https://user-images.githubusercontent.com/25544824/212624650-651ff769-018c-4945-a718-70cc1d9fb7c1.png">
