### ISSUE TITLE
When you do /logout and there is no pllatform template is broken and no butons are showing

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#413]
In case there is no platform remove the space before '?' to make sure template is still recognizable.

![WhatsApp Image 2023-01-10 at 3 31 50 PM](https://user-images.githubusercontent.com/25544824/211621103-6df1d27f-3dfe-4288-bcf5-a43a37465910.jpeg)

**Comment by JerryVDP** [comment]
The problem is not the extra space, but rather the missing platform name, please note the message:
_Are you sure you want to logout from **[MISSING PLATFORM NAME]**? 
(This means your current saved settings will be lost)_

How should I handle this?
@assafza

**Comment by assafza** [comment]
@JerryVDP instead of Platform name write Fredo.
"Are you sure you want to logout from Fredo?''

**Comment by assafza** [comment]
@JerryVDP lets make this for everything that is not Email | Monday | Trello | Workflowy
