### ISSUE TITLE
Add mixpanel event when a disregarded message arrived

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#414]
We should send an event when this type of message occurs.

I added a new property to the event "ADDED NEW ITEM" called "escaped" which should be Yes/No.
If a message is escaped it should be Yes, other wise send this property as empty or with "No" value.

**Comment by lotem-vanunu** [comment]
the event "ADDED NEW ITEM" is sent only in Wmail, Tello, Workflowy and Monday, not in any message to Fredo.

**Comment by assafza** [comment]
@lotem-vanunu looks like it is working also outside of platform :)
Am I missing anything?

![Image](https://user-images.githubusercontent.com/25544824/215330413-616bff23-3967-45cd-989f-8c2079e88045.png)
