### ISSUE TITLE
Onboarding has completely gone wrong on Staging

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#421]
- [x] the privacy message is showing without template
- [x] I click reminders/transcribe nothing happens
- [x] Please send a report investigating what has happenned there please. because I have tested it and all was fine, I wonder which commits joined staging that broke it like that.

<img width="1001" alt="Screenshot 2023-01-21 at 9 31 50" src="https://user-images.githubusercontent.com/25544824/213849083-436163ac-569d-48a1-9940-17b36bbed262.png">

**Comment by JerryVDP** [comment]
https://docs.google.com/document/d/1BYymipGV_Xzt1983-tH9StAx1v62rNj5nYlziRZTeF8/edit?usp=sharing
