### ISSUE TITLE
change /reminder help command message

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#422]
When user select reminder in the help menu we should print the following message:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764531637216696&cot=14

**Comment by lotem-vanunu** [comment]
The new message doesn`t fit to the button template -"View all reminders"

**Comment by assafza** [comment]
Hi @lotem-vanunu this is the correct template:

You can set reminders with Fredo by sending:
*reminder* followed by *date* followed by *time* followed by the *reminder text*.

*Example*:
reminder 2h buy milk
reminder 30m buy milk
reminder 16:30 buy milk
reminder tomorrow 15:00 buy milk
reminder Monday 10:00 buy milk
reminder 26/09 buy milk

You can also try to use natural language and Fredo will try to understand your reminder.

*Example*:
Remind me to cut the grass tomorrow @8AM

As long as you start with the word *reminder* or *remind* Fredo will try to understand your reminder.
