### ISSUE TITLE
#hashtags for next message

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#429]
#שם_רשימה

שתגרום לזה שההודעה הבאה בתור (טקסט/קולית/תמונה/לא משנה) תנותב לרשימה שצויינה.

זה עוד דוגמא לפיצר שאני מקווה שיחסית קל למימוש.
והפעם מרגיש לי שהוא נותן ערך משמעותי.

**Comment by adidacta** [comment]
@assafza we decided we won't use this option but rather go with your suggestion to ask the user what to do when user sends a voice call (not forward).
I suggest we close this as "not planned"
