### ISSUE TITLE
Enable user send a bug report

### ISSUE THREAD

**Issue by liatzionimorad** [fredo-ai/Fredo-Public#77]
As a user, I'd like to send the bot a bug report, from within whatsapp, without leaving to another app/email.

/email I have a problem with sharing my groceries list

Should let us know (how? Email to bugs@fredo.ai   & the user's email?)
(In the future - open a ticket in our ticketing system. not github. Note - the user's bug report can contain private information)

Fredo should auto-reply:

We got your bug report, ticket number 23421 was created in our system and sent to your.email@gmail.com

@assafza  we need to better define this is a feature requested by Ron

**Comment by assafza** [comment]
1. For a start lets add a new flow for /bug
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764527378201674&cot=14

2. When user is sending his text we will email this to our email "support@fredo.io":
**Subject**: New support ticket <> {{whatsapp number}}
**Body**: A user just submitted a bug through the Fredo bot:
User description of the bug: {{user's description}}
Number: {{user number}
Platform used: {{platform}}

3. Add mixpanel event for bug submission:
https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0

**Comment by assafza** [comment]
Looks like the feature is not working, why is it under testing? am I missing something? @JerryVDP 
<img width="748" alt="Screen Shot 2022-06-29 at 11 24 29" src="https://user-images.githubusercontent.com/25544824/176389115-776d6473-ee66-4f83-9f09-9a485436fe09.png">

**Comment by assafza** [comment]
The email formatting is off and missing data:
<img width="786" alt="Screen Shot 2022-07-06 at 14 16 34" src="https://user-images.githubusercontent.com/25544824/177539395-f3730bc1-9a9a-4d11-b705-69211abf2982.png">

**Comment by assafza** [comment]
@JerryVDP have you seen the previous comment I sent?
The email is still coming in empty & all in one line.
Please make sure the lines are breaking and there is the user's info inside the body and subject.
