### ISSUE TITLE
Whatsapp to Whatsapp flow

### ISSUE THREAD

**Issue by liatzionimorad** [fredo-ai/Fredo-Public#92]
[12:54, 28.3.2022] רון גרוס: Issue 2:
From Ron :

As a user, I'd like to send Fredo texts, and he will text me back - in different whatsapp groups that I have with him.

E.g. Everything I text him, will be texted back to me in another group "Fredo & me"
If I text "#urgent bla bla", he will text me "bla bla" in another group titled "Urgent" (that has Fredo & me).

What do you think?
It's useful to people who don't currently use a task management system - but rather use whatsapp as their system.

@assafza let's discuss I like it

**Comment by assafza** [comment]
@liatzionimorad  I am not fully sure I understand the "why" here.
Can you elaborate a use case a user will need this ability?

If I understand correct, you want the ability that an incoming message to Fredo will be sent to other groups Fredo is a member in.
In that case, why not go to the group and write this myself? I might not fully understand the need so it will be helpful if you can explain the "why" aspect here:

"As a user, I'd like to send Fredo texts, and he will text me back - in different whatsapp groups that I have with him **so that________"

**Comment by liatzionimorad** [comment]
@ripper234  best you answer :-)

**Comment by elihaidv** [comment]
From what I know WA doesn't allow bots to join groups.
I tried add Fredo to group, but no success.
Shlomi from MeserGo said he has unofficial bot that can be join groups.
